✨ Feat : 로그인 API 추가
Challenge-Hanbang-E/Hanbang-E pull request #16
Opened 2023-01-09 07:38 UTC by seunGit

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [x] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요 
- 로그인 기능 추가
- 구현된 코드를 테스트하는 테스트 코드 추가

## 작업 및 변경 사항 
- 로그인 기능 구현
- Repository계층 단위 테스트 코드 추가
- Service계층 단위 테스트 코드 추가
- Controller계층 통합 테스트 코드 추가

### 테스트 결과 
- 테스트 코드 실행 특이사항 없음

close #9

2023-01-09 10:29 UTC, m1naworld reviewed
고생하셨습니다 👏🏻

2023-01-09 10:29 UTC, m1naworld commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +
제가 알기로는 `@DataJpaTest` 어노테이션 안에 `@Transactional`에 의해 하나의 테스트 메서드가 종료될 때마다 테스트 메서드 내부에서 생성했던 데이터를 rollback 한다고 알고 있습니다. ❗️ 혹시 이를 적용하고 안하고의 차이를 알 수 있을까요?! 혹시나 안할 경우 어떠한 에러가 나는지도 궁금합니다👀

2023-01-09 10:33 UTC, m1naworld reviewed
현재 jwt를 검증하는 로직은 없는 것 같은데 구현 중이신걸까요?!

2023-01-09 10:44 UTC, tjvm0877 approved these changes
저희가 짠 API명세서의 내용과 로그인 기능이 실제로 반환하는 내용이 차이가 있는 것 같습니다. 확인 부탁드리고 명세서 혹은 코드를 수정해서 맞춰주시면 될 듯 합니다.
제 개인적인 의견이지만 로그인할 때 주소와 이메일은 반환할 필요가 없다고 생각합니다.

2023-01-09 10:44 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +    }
저희 API명세서의 반환타입이랑 다르게 구현이 되어있네요. API명세서 확인해주시고 API명세서나 본 코드를 수정하던가 해야될 듯 합니다.

2023-01-09 10:44 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +        assertThat(msg3).isEqualTo("비밀번호가 일치하지 않습니다.");
하나의 테스트안에 이렇게놔도 괜찮아보이네요. 저는 전부다 분리하긴 했는데 고민해볼 여지가 있는 것 같습니다. 다른분들의 의견이 궁금합니다.

2023-01-09 10:47 UTC, tjvm0877 requested changes
잘못 승인 했습니다. 코멘트 확인해주세요 ㅠ

2023-01-09 11:24 UTC, m1naworld commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +        assertThat(msg3).isEqualTo("비밀번호가 일치하지 않습니다.");
저도 모두 분리했는데 🤣 그래서 중복되는 코드가 많습니다. 생각해보면 하나의 기능을 검증하는 테스트인데 결과에 따라 여러 테스트로 나눈 다는 것이.. 🤔 위의 코드가 기능 별 예외처리 및 직관적으로 보여 더 좋아보입니다. 테스트 코드 리팩토링시 우선 하나로 통합하는 방향으로 가보는건 어떨까요?!

2023-01-09 11:25 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +        assertThat(msg3).isEqualTo("비밀번호가 일치하지 않습니다.");
@m1naworld 근데 또 생각해보면 하나의 기능에 대한 테스트코드가 많아질수록 점점 단위테스트의 의미가 퇴색될 수 있다는 점이 있을 것 같네요.

2023-01-09 11:34 UTC, seunGit commented on src/main/java/com/hanbang/e/common/jwt/JwtUtil.java
> +    }
@m1naworld 토큰 검증하는 단계 입니다.

2023-01-09 11:34 UTC, seunGit commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +    }
@tjvm0877 API 명세서 반환타입은 컨트롤러 계층에 구현했습니다. Service 계층의 반환타입은 ServiceTest코드 작성을 위해 구현되었습니다.

2023-01-09 11:34 UTC, seunGit commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +
`AfterEach` 사용유무와 상관없이 실행이 잘 되는걸 확인했습니다. <br> 말씀하신대로 `@DataJpaTest`  내의  `@Transactional`이 작동하여 필요없는 코드로 생각됩니다. 추후 학습 후 말씀드릴 수 있도록 하겠습니다.

2023-01-10 05:47 UTC, tjvm0877 approved these changes

2023-01-10 06:47 UTC, m1naworld approved these changes
고생하셨습니다 👏🏻

2023-01-10 06:47 UTC, m1naworld commented on src/test/java/com/hanbang/e/member/util/JwtUtilTest.java
> +    }
좋습니다!

2023-01-10 06:47 UTC, m1naworld commented on src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
> +        when(memberRepository.findByEmail(any())).thenReturn(Optional.of((memberLoginReq.toEntity())));
stub 부분에서 memberLoginReq.toEntity가 아닌 member가 와야할 것 같습니다. ! 그 이유에 대해 한번 생각해보시고 다음 리팩토링 때 참고 부탁드립니다 🙇‍♀️ 또한, 현재 httpServletResponse는 사용하지 않는 코드로 보입니다. 이런 경우에는 지워주시면 감사하겠습니다! 🫡

2023-01-10 06:55 UTC, tjvm0877 approved these changes

2023-01-10 11:20 UTC, merged