✨ Feat : 주문생성/삭제 동시성 제어
Challenge-Hanbang-E/Hanbang-E pull request #63
Opened 2023-01-19 09:58 UTC by yejin0718

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요 
- 주문생성/삭제 동시성 제어 추가

## 작업 및 변경 사항 
- RedissonLockFacade작성
- 테스트 코드 작성
- controller 수정

### 테스트 결과 
- 내용을 적어주세요.

### 공유 하고 싶은 내용 및 참고 자료
- 내용을 적어주세요.

close #62

2023-01-19 11:02 UTC, tjvm0877 requested changes
P1: 코멘트 확인 부탁드립니다.

2023-01-19 11:02 UTC, hyunmuam commented on src/main/java/com/hanbang/e/order/facade/OrderRedissonLockFacade.java
> +        String inserKey = String.valueOf(1+key);
P1: `insertKey`를 `inserKey`로 오타난 것 같습니다. 확인부탁드립니다.

2023-01-19 11:02 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/order/controller/OrderController.java
>  	}
P1: 파사드 패턴을 쓰신 것 같은데, 파사드 패턴을 Controller계층에서 직접 접근하는것이 맞는지 한번 알아봐야 될 것 같습니다.

2023-01-20 02:39 UTC, yejin0718 commented on src/main/java/com/hanbang/e/order/facade/OrderRedissonLockFacade.java
> +        String inserKey = String.valueOf(1+key);
네 수정하겠습니다!

2023-01-20 02:39 UTC, yejin0718 commented on src/main/java/com/hanbang/e/order/controller/OrderController.java
>  	}
넵 확인해보고 수정하겠습니다

2023-01-20 07:57 UTC, tjvm0877 approved these changes

2023-01-21 02:04 UTC, merged