✨ Feat : 회원가입 API 추가
Challenge-Hanbang-E/Hanbang-E pull request #8
Opened 2023-01-06 13:36 UTC by seunGit

## PR 타입

- [ x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ x] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요 
- 회원가입 기능 추가
- 구현된 코드를 테스트하는 테스트 코드 추가

## 작업 및 변경 사항 
- 회원가입 기능 구현
- Repository계층 단위 테스트 코드 추가
- Service계층 단위 테스트 코드 추가
- Controller계층 통합 테스트 코드 추가

### 테스트 결과 
- 테스트 코드 실행 특이사항 없음

close #4

2023-01-06 13:55 UTC, m1naworld approved these changes
👏🏻👏🏻 테스트 코드까지 !! 고생하셨습니다 ! 👏🏻

2023-01-06 13:55 UTC, m1naworld commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +        Member member = new Member(requestCreateMember.getEmail(), requestCreateMember.getPassword(), requestCreateMember.getAddress());
**엔티티 생성시** 정적팩토리를 기본으로, 파라미터가 많고 요청 객체에서 엔티티를 생성할 수 없는 경우 빌더패턴을 사용하기로 컨밴션을 정하였습니다! 컨벤션 한번 확인 해주세욥!!

2023-01-06 14:28 UTC, tjvm0877 requested changes
코멘트 확인 부탁드립니다.

2023-01-06 14:28 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/dto/RequestCreateMember.java
> +    private String password;
valid가 실패했을 때 관련된 Exception핸들러가 추가되었음 좋겠습니다. 

제가 작성한 코드는 `GlobalExceptionHandler`에 다음과 같이 `ExceptionHandler`를 추가해줬습니다.
```java
  @ExceptionHandler(MethodArgumentNotValidException.class)
  public ResponseEntity<?> validException(MethodArgumentNotValidException e) {
  String errorMsg = e.getBindingResult().getAllErrors().get(0).getDefaultMessage();
  CMResponseDto response = CMResponseDto.builder().result("fail").msg(errorMsg).data(null).build();
  return new ResponseEntity<>(response,HttpStatus.BAD_REQUEST);
  }
```

2023-01-06 14:28 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/dto/RequestCreateMember.java
> +public class RequestCreateMember {
저희 노션 컨벤션에 Dto 네이밍 부분 확인해주세요~

2023-01-06 14:28 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/dto/ResponseMember.java
> +public class ResponseMember {
마찬가지로 DTO네이밍 규칙 확인 부탁드려요.

2023-01-06 14:28 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/dto/ResponseMember.java
> +    private String address;
DTO관련 컨벤션을 보시면 저희는 DTO필드에 빈줄을 빼기로 했습니다. 확인하고 반영 부탁드립니다.

2023-01-07 09:30 UTC, tjvm0877 requested changes
고생하셨습니다. 몇가지 코멘트를 남겼는데 확인 부탁드립니다. 민식님의 코드를 보고있으니 정상적엔 요청 뿐만 아니라 처리되면 안되는 비정상적 요청에 대해서도 테스트를 해야되겠다는 생각이 드네요. 쪼금만 더 고생하시면 될 것 같습니다!

2023-01-07 09:30 UTC, hyunmuam commented on src/main/java/com/hanbang/e/member/dto/MemberCreateReq.java
> +    private String address;
와우... 이렇게보면 필드간 빈줄을 추가 해야겠다는 생각이 들긴하네요.... 이부분 한번 논의 해보시죠

2023-01-07 09:30 UTC, hyunmuam commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +        Member member = Member.of(memberCreateReq.getEmail(), memberCreateReq.getPassword(), memberCreateReq.getAddress());
meberCreateReq에서 정의한 ToEntity를 사용하면 더 깔끔해보이긴하는데 이것도 논의해봐야 될 것 같습니다.
```java
Member member = meberCreateReq.toEntity();
```

2023-01-07 09:30 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +    }
좋은 테스트 코드 같습니다!
추후 중복된 이메일 요청, 정해진 비밀번호 형식을 지키지 않은 요청 등 처리되면 안되는 요청들이 잘 막히는지도 확인해보면 좋을 것 같네요.

2023-01-07 09:30 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +    }
현재있는 테스트는 하나이고, 테스트에서의 하나의 트랜잭션이 끝나는 시점에서 롤백되기 때문에 이 부분은 필요 없을 것 같습니다.

2023-01-07 10:35 UTC, m1naworld commented on src/main/java/com/hanbang/e/member/dto/MemberCreateReq.java
> +
메소드 사이에는 빈 줄을 삽입을 삽입해주세요! 

저희가 따르기로한 캠퍼스 핵데이 입니다. 참고 해주세요! 🫡
https://naver.github.io/hackday-conventions-java/#blankline-between-methods

2023-01-09 05:44 UTC, tjvm0877 requested changes
고생하셨습니다! 코멘트 확인해주세요.

2023-01-09 05:44 UTC, tjvm0877 commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +    }
아주아주 개인적인 생각이지만 다른 메서드와 중복되는 부분이없어 아직은 따로 뺄 이유가 없어보이긴 합니다.

2023-01-09 05:44 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +    }
회원가입부분에서 쓰이고 있지 않습니다. 삭제해도 될 것 같습니다.

2023-01-09 05:44 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +        Member member = new Member("이메일","비밀번호","주소");
`setup()`에서 회원을 이미 만들어주고 또 새로 만드는 이유가 없어보입니다. 다른 메소드가 없기 때문에 `BeforeEach`는 삭제해도 될 듯 합니다.

2023-01-09 05:44 UTC, tjvm0877 commented on src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
> +        assertThat(memberResp.getEmail()).isEqualTo(memberCreateReq.getEmail());
이메일 뿐만 아니라 회원가입 시 들어간 모든 데이터를 확인해보면 좋을 것 같습니다.

2023-01-09 06:08 UTC, tjvm0877 approved these changes
확인했습니당~

2023-01-09 06:11 UTC, m1naworld commented on src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
>      private MemberService memberService;
혹시 Mock 객체에서 진짜 memberService를 주입하는 코드로 변동된 이유가 있을까요??

2023-01-09 06:16 UTC, m1naworld reviewed
고생하셨습니다 👏🏻

2023-01-09 06:55 UTC, merged

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +        Member member = new Member(requestCreateMember.getEmail(), requestCreateMember.getPassword(), requestCreateMember.getAddress());
컨벤션 확인하고 수정하겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/dto/ResponseMember.java
> +    private String address;
확인하고 반영하겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/dto/ResponseMember.java
> +public class ResponseMember {
확인하고 반영하겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/dto/RequestCreateMember.java
> +public class RequestCreateMember {
확인하겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/dto/RequestCreateMember.java
> +    private String password;
코드 확인하고 적용시켜보겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +    }
확인했습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +        Member member = Member.of(memberCreateReq.getEmail(), memberCreateReq.getPassword(), memberCreateReq.getAddress());
추후 논의 후 리팩토링 여부 확인하면 좋을 것 같습니다.

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/dto/MemberCreateReq.java
> +    private String address;
이렇게 보니 또 다르네요 ㅠㅠ 확인했습니다.

2023-01-09 11:35 UTC, seunGit commented on src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
> +        assertThat(memberResp.getEmail()).isEqualTo(memberCreateReq.getEmail());
`address` 데이터 추가 반영하겠습니다.

2023-01-09 11:35 UTC, seunGit commented on src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
> +        Member member = new Member("이메일","비밀번호","주소");
`BeforeEach` 삭제하고 반영하겠습니다.

2023-01-09 11:35 UTC, seunGit commented on src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
> +    }
삭제처리 하겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/main/java/com/hanbang/e/member/service/MemberService.java
> +    }
코드 정리해보겠습니다!

2023-01-09 11:35 UTC, seunGit commented on src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
>      private MemberService memberService;
<img width="844" alt="스크린샷 2023-01-09 오후 3 24 31" src="https://user-images.githubusercontent.com/110602191/211251355-3fab5b56-5402-41ac-a89a-2efbf153948e.png">
InjectMocks 어노테이션은 Mock 어노테이션이 붙은  객체를 주입시켜 줍니다.<br>
객체 주입을 하지 않고 적용시키려다 보니 @Autowired 를 사용한 것 같습니다. (memberRepository 누락)<br>
코멘트 확인 하고 위 그림과 같이 수정하여 반영하니 테스트가 통과되었습니다. 수정하고 더 공부하겠습니다.<br>
참고 블로그 : https://lemontia.tistory.com/951